### ISSUE TITLE
snow_leopard theme

### ISSUE THREAD

**Issue by adriadri25** [w0lfschild/cDock-Issue-Tracker#259]
Hi, I really appreciate your work.
I looking forward to snow leopard theme original looking.
Is there any possibility to add the original separator.png and the frontline.png to this theme?
Thank you in addvance!
Adrian.H
![separator](https://user-images.githubusercontent.com/62297831/76875319-b45f6d00-6870-11ea-966a-4608dbccb6d1.png)
![frontline](https://user-images.githubusercontent.com/62297831/76875343-ba554e00-6870-11ea-83be-deca5078834c.png)

**Comment by w0lfschild** [comment]
Just for fun I'll put out a $20 (PayPal) bounty for anyone that can make a ~95% accurate representation of the 10.6 Dock as a theme for cDock 4. 

Indicators
Separator Image
A cleaned up background image from the 10.15 theme with the bottom bar imbedded

For reference see below

![https://i.redd.it/ots4u2oxtjy31.jpg](https://i.redd.it/ots4u2oxtjy31.jpg)

**Comment by jsteweii** [comment]
Here is my take on it, quickly whipped up:-). Some notes, the separator, dock height and angles aren't quite there due to the limitations dock/cDock has (scaling, distance from the bottom etc.).  I'll upload here and in Discord:-).

<img width="1680" alt="Screenshot 2020-11-20 at 18 19 47" src="https://user-images.githubusercontent.com/30780358/99830423-fbb79f00-2b5d-11eb-998a-fce66e94baba.png">

[Snow Leopard.zip](https://github.com/w0lfschild/cDock-Issue-Tracker/files/5575139/Snow.Leopard.zip)
