### ISSUE TITLE
Show only active dock items cannot be reset to show ALL

### ISSUE THREAD

**Issue by NormG1** [w0lfschild/cDock-Issue-Tracker#285]
**Describe the bug**
I tried to update to the new cDock Version 4, while still on Catalina. V3 was working perfectly and yes, my SIP is disabled.

About half of it works, basically the commands that could also be found in Cocktail or Onyx that are already built into the OS by Apple.

No customization that is built into cDock v4 works anymore. No themes, no borders, no colored backgrounds, no shadows, no dimming of inactive apps, nothing works.

I have tried the following:
Reboot. No change.
Uninstall and reinstall cDock. No change.
Launch Recovery and then turn off the Startup Password Lock so I could boot into Safe Mode.
Boot in Safe Mode. No change.
Boot from an external drive into Big Sur. No change.

One thing I could duplicate is for sure a bug and is documented below.

**To Reproduce**
Launch cDock.
Go to Dock Settings Screen
Click on "Show Only Active Apps"
Only Active Apps now appear in the dock.
Unclick on "Show Only Active Apps"
Just to be double sure, I saved changes and restarted the dock.

Sorry, I was now stuck with only Active Apps showing. No matter if cDock was loaded or not. There is no way to go back to showing all apps except to reset the dock in Terminal with the command: defaults delete com.apple.dock; killall Dock

Now I am back to a normal MacBook Catalina machine. I have removed all vestiges of anything associated with cDock V4 and plan to go back to 3.1.2 right after I submit this bug and hopefully get my life back. 

My machine is unusable due to muscle memory from years of using cDock. I used to know where everything was in my dock, not the mess that Apple creates as my default dock. So if I can get 3.1.2 up and running again, I'll be good until we can figure out why cDock V4 is simply NOT WORKING AT ALL,.

**Expected behavior**
I expect it to work as well as Version 3 worked, with maybe a few bugs. I did not expect a total failure to modify the dock.

**Screenshots**
I can do them if you need them but they look just like an Apple Standard dock.

**Desktop (please complete the following information):**
 - OS: Mac OS both Catalina 10.15.6 and Big Sur OS11 Public Beta #6

**Additional context**
Since V4 is working for others, what about my machine is different? Because in Safe Mode, there is nothing but pure Apple running. No third party stuff, no browsers, no ad blockers, nothing but Apple Factory Default and still cDock will not do anything. It launches, it runs, all the screens to set the preferences appear and work (i.e. every box that can be checked seems to work in thay the check appears and disappears). The program just does nothing at all to the dock. 

The next step is to run an EtreCehck Report and see what else might be running in the background that could affect the dock in V4 that didn't affect the dock in V3.

**Comment by NormG1** [comment]
I was able to go back successfully to 3.1.2. Everything works except being able to manage or modify the active app indicators. The are white and they cannot be modified in any way. But everything else I need or use is back to working properly. V4 is still a problem though.

**Comment by etrahretep** [comment]
Exactly the same issue on 2 of my 3 machines.

**Comment by etrahretep** [comment]
Version 4.2.2 doesn't fix the issue.

**Comment by NormG1** [comment]
Thanks for confirming that I am not the only one that is experiencing problems with V4 of cDock.

**Comment by etrahretep** [comment]
4.2.2 is pulled (rollback to 4.1.5). 4.1.5 refuses to work on BS beta 7/8. Very disappointed sofar. Bought version 4 (and 3 in the past). Never had a good experience. Could the developer please project a time-path in which he could deliver a working version?
No response sofar from Paddle or the developer....

**Comment by w0lfschild** [comment]
@etrahretep 

Well the beta has been making changes to the Dock which have been causing issues. I wouldn't expect anything working on beta 6+ until after the GM.

Part of using something like cDock is that it can break with any update. Not really anything I can do about that.

@NormG1 

In regards to your original issue. It's not really a bug. It's just how the Dock works, everything shown by the Dock is stored in `~/Library/Preferences/com.apple.dock.plist` when you enable `Show only active dock items` that file is just going to contain the active apps. Disabling `Show only active dock items` will not magically bring back your original dock layout.

If you want to use `Show only active dock items` temporarily turn on `auto-save preference backups` and then restore from a backup to get back to the Dock layout you had before.

As for the customization not working, I believe that might have been a licensing issue with versions above 4.1.5

**Comment by etrahretep** [comment]
@w0lfschild 
Understood. But it seems to me that part of being a developer of paid software is to make it work with any update.
The "Not really anything I can do about that" is a bit easy...

**Comment by w0lfschild** [comment]
@etrahretep 

Normally I would agree that point updates (eg 10.15.**2**) shouldn't generally break existing software, cDock is different since it is loading live code into an application I do not make `Dock.app`.

Any changes Apple makes to the Dock have the potential to break cDock (the theming functionality) however, maybe you have or haven't noticed, the App itself (that you use to set the preferences) has never broken to my knowledge. I'd imagine if you downloaded any version released in the last 3-4 years you could still get it to open up fine on Big Sur. 

On top of that code injection (the theming functionality) is not something that I would say is Apple approved, hence why users have to disable SIP just to get cDock to function.

Unlike a point update betas can change core functionality significantly between releases and it's often not worth the time to fix a bug until it is known whether or not that will be the functionality come release time. For example there was a crash when right clicking the Dock on beta 6. I had someone else write a fix for me, that crash is now gone in beta 7/8. That was wasted time and if it hadn't been a friend who did the investigation and wrote the fix for free I would have also had to waste money having someone investigate/write a patch that was ultimately worthless. I don't make enough money from cDock to just slam out hundreds of hours working on bug fixes, support, maintenance, emails, etc. Like the build number of the cDock bundle is at 11,100 that means even if it only took 1 second to build, restart and load into the Dock, I've spent over 3 hours (11k / 60 / 60) just waiting for Xcode to build the cDock plugin.

To be honest I only released v4 during the Big Sur beta because I assumed I'd have a bunch of people emailing me to complain about cDock v3 not working and I had some extra free time because of COVID.

Finally cDock relies on a ton of 3rd party code which always has the potential to break with updates and I just have to wait/hope that it is fixed by the original authors, if you check out the credits in the app preferences you'll see all this:

- Privileged scripts : [STPrivilegedTask](https://www.github.com/sveinbjornt/STPrivilegedTask)
- Code Injection : [mach_inject](https://github.com/rentzsch/mach_inject)
- Sales & Licenses : [Paddle](https://paddle.com/)
- Launch at login : [StartAtLoginController](https://github.com/alexzielenski/StartAtLoginController)
- Method Swizzling : [ZKSwizzle](https://github.com/alexzielenski/ZKSwizzle)
- Mission control auto expand : [forceFullDesktopBar](https://github.com/briankendall/forceFullDesktopBar)
- Analytics : [appcenter-sdk-apple](https://www.github.com/microsoft/appcenter-sdk-apple)
- Updates : [Sparkle](https://www.github.com/sparkle-project/Sparkle)
- Auto move : [LetsMove](https://www.github.com/potionfactory/LetsMove)
- Object Hooking : [JSRollCall](https://github.com/jslegendre/JSRollCall)

Currently the 10.14.6 security patch broke [mach_inject](https://github.com/rentzsch/mach_inject), which breaks cDock (the theming functionality) so, I'll have to wait and see if that ever gets fixed. 

Kind of getting into ramble/rant territory here but I do have a fix which you're welcome to try here (it also fixes the issues with versions above 4.1.5 not loading):

https://github.com/w0lfschild/app_updates/raw/master/Beta/cDock_4.3.1.zip

Lastly I'm closing this issue because the original issue `Show only active dock items cannot be reset` is not something I'm likely going to try and write a fix for.
