### ISSUE TITLE
not working on big sur 

### ISSUE THREAD

**Issue by mytesteraccount** [w0lfschild/cDock-Issue-Tracker#287]
themes are not changing

**Comment by NormG1** [comment]
If you ant the bugs fixed, you are going to need to write a full bug report. Any developer who sees 4-word bug reports like yours generally assumes the problem is with you and not the program.

Write down every little thing. There are templates for submitting bug reports that will tell you exactly how to write one that is helpful.

Describe your hardware and software setup.
Describe what you tried to do.
Describe what you expected to happen.
Describe what actually happened.
Describe any steps you may have taken to troubleshoot or fix the issue. Restart? Safe mode? Downgraded to a previous version?

What you wrote will not help the developer fix the issue because he has no idea where to even start.

Even a report "Crashes on launch" needs more description to be useful.

BTW, I believe you about v4. It doesn't work in some circumstances and on some machines. It was written for Big Sur, I am still on Catalina, and it appears not to be backwards compatible.

**Comment by w0lfschild** [comment]
@NormG1 Yeah a few words doesn't help me at all but it's fine, the average user doesn't know any better, they just want their stuff to work.

As for it not working, I'm thinking it has something to with user permissions/licensing. Version 4.1.5 should work. It's definitely not that it doesn't work on macOS 10.15 because I have a MacBook on 10.15.6 which it runs fine on.

My guess it's an issue using `/Users/Shared/macenhance` for the licenses instead of `~/Library/Application Support/cDock`

**Comment by etrahretep** [comment]
Version 4.1.5 is working on 10.15.6 although with quirks. Still straggler indicator and repeated dock crashes.
Why rollback from 4.2.2? That one works OK on my iMac running Big Sur b6

**Comment by w0lfschild** [comment]
Merging with https://github.com/w0lfschild/cDock-Issue-Tracker/issues/291
