### ISSUE TITLE
Big Sur - Adjust the space between dock and edge of screen.

### ISSUE THREAD

**Issue by r3volution11** [w0lfschild/cDock-Issue-Tracker#295]
**Is your feature request related to a problem? Please describe.**
With Big Sur, Apple decided to move the dock further away from the edge of the screen to match the iOS/iPadOS aesthetic. It'd be great to remove that spacing. Or maybe even increase it if that suits people's fancy.

**Describe the solution you'd like**
The ability, perhaps with a slider, to adjust how close to the edge of the screen the dock is placed.

Another possibility would be to decrease the dock padding but that would be more of a hack-like fix.

**Describe alternatives you've considered**
In the meantime, I've made my dock icons smaller so that the dock takes up a similar amount of space to what it was pre-Big Sur.

**Additional context**
N/A.

**Comment by w0lfschild** [comment]
Actually the Dock didn't move farther away from the edge of the screen. They shifted the indicators and app icons up about 4 pixels and then just raised the bottom edge of the background layer 12 pixels and gave the bottom edges rounded corners like the top edges.

The tile sizing is the same as previous versions.

It's unlikely that I'm going add fine-grain controls for everything beyond what already exists. Sadly I have never been able to find what handles the tile mouse event region, outside of something really hacky I can't really move where the tiles are otherwise you get an issue where the image and mouse event region don't line up.

If all you want is old look back cDock can already do that, and more on Big Sur.

![Screen Shot 2020-11-15 at 1 29 39 PM](https://user-images.githubusercontent.com/1920148/99197315-9e2ee700-2746-11eb-916f-892b39d3a52f.png)

**Comment by r3volution11** [comment]
Interesting. When I booted up Big Sur for the first time it took ~5-8 pixels of additional space and couldn't figure out how to get it back outside of changing icon size down 2 pixels which still left a bit less. I saw it based on having apps maximized (not full screen) before the upgrade and then changed one app to maximized to see the difference.

!(My Screenshot)[https://r3v.in/F2e/Screen-Shot-2020-11-15-16-52-03.58.png]

Your screenshot makes it look like the icons are closer to the edge than mine are. Am I missing a setting? Would another theme bring them closer?

**Comment by InDoubt** [comment]
I'm sorry to say, r3volution11,
The answer was "Not possible with my knowledge." on Aug 10 2019!
https://github.com/w0lfschild/cDock-Issue-Tracker/issues/177
😞

**Comment by w0lfschild** [comment]
Yeah moving the icons out of their `Space` would create the same issues as https://github.com/w0lfschild/cDock-Issue-Tracker/issues/124

To see what I'm talking about: pin the Dock to the top and turn on magnification then mouse over the dock and see what happens.

Sadly it's just too buggy for me to want to add more implementations for moving the icons around the screen.

Closing the issue for now.
